language: python
python: 3.6
install:
- pip install pipenv
- pipenv install

script:
- black -c .
- black --check blogsite/blogging blogsite/blogsite blogsite/polling
- python blogsite/manage.py test
